stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node
  script:
    - echo "Start building"
    - npm install
    - npm build
    - echo "Done!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build

test:
  stage: test
  image: node
  script:
    - echo "Start testing"
    - npm install
    - CI=true npm test
    - echo "Done!"

deploy_development:
  stage: deploy
  script:
    - echo "Deploying to the development server"
    - cp -rv build/* /var/www/html/<destination_folder>/
    - echo "Deployed"
  environment:
    name: development
  only:
    - development

deploy_stage:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
  script:
      - echo "Deploying to the stage server"
      - cp -rv build/* /var/www/html/<destination_folder>/
      - echo "Deployed"
  environment:
      name: stage
      url: <your deployment url>
  only:
      - master

docker-build:
  stage: docker-build
  image: docker:latest
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"